name: Nami Photos
author: Kaitlyn Delacruz
url: https://namiphotos.studio
aboutme: >-
  I am currently a Sait Journalism student my primary major currently is in
  Photo.


  Currently I live in Calgary Alberta, Canada
