name: Nami Photos
author: Kaitlyn Delacruz
url: https://namiphotos.studio
aboutme: >-
  Hello,\

  My name is Kaitlyn Delacruz friends call me by "Nami". Currently I am a SAIT Journalism student currently in the photo-major for the program.\

  Currently I live in Calgary Alberta, Canada.\

  My goal is to strive and work to become a photojournalist and travel the world showcasing the many wonders and even sit down and teach in anther country.


  # Current Gear and Equipment.


  * Macbook Air M1

  * Sony a7ii

  * Zoom F1-LP

  * Sony 28-70mm f3.5-56

  * Tamron 28-200mm f2.8

  * Godox V860 x2 and X-Pro for Sony


  - - -


  If you wish to request more information or would like to contact me please fill in the intake form linked below.
